services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=lab2pass
      - POSTGRES_USER=natalia
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

  etl:
    container_name: lab2_etl
   # restart: always
    build: .
    environment:
      - DB_URL=postgresql+psycopg2://natalia:lab2pass@db:5432/shelter
    command: https://data.austintexas.gov/resource/9t4d-g238.json
    # command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - db


volumes:
  db_data: